### PR TITLE
Add support for trimming contents of xml values

### PR DESCRIPTION
**Pull request by kabir**

### CODE REVIEW

**Review by luck3y — APPROVED** [review]
LGTM, thanks @kabir!

**Comment by kabir** [comment]
@goldmann @luck3y Can it be merged?

**Comment by goldmann** [comment]
Merged, sorry!

**Comment by kabir** [comment]
Thanks @goldmann !

**Comment by goldmann** [comment]
I was not watching this repo so I did not get initial notification, this was fixed.

**Pull request merged**
